### PR TITLE
Creating Accessibility

### PR DESCRIPTION
**Pull request by orozCoding**
**🟢  In this branch, we added accessibility to the project. We did the following changes:**
 
_We are not sure if we are supposed to link the old code or the new code, so we are linking first the new code with the changes and, just in case, we are linking also at the bottom the old code lines_

- Page titles → We changed the title to a more descriptive title. 
https://github.com/orozCoding/myportfolio/pull/8/files?authenticity_token=moLCNx7Ft%2F9X%2FTL0g45XwcaG96u8OrpFJ%2BYsnAqq7NATMa%2FwuVIx8wrzgFArtxLuJ4lxg4urUr4H0gMI9mZ0Dg%3D%3D&file-filters%5B%5D=.html#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L8

- Image text alternatives → We modified the alt attribute for several images to make them more descriptive.
https://github.com/orozCoding/myportfolio/pull/8/commits/cef462074275ef20e2351585dc09a04e8c8c1cc5#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L32
https://github.com/orozCoding/myportfolio/pull/8/commits/cef462074275ef20e2351585dc09a04e8c8c1cc5#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L70
https://github.com/orozCoding/myportfolio/pull/8/commits/cef462074275ef20e2351585dc09a04e8c8c1cc5#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L91
https://github.com/orozCoding/myportfolio/pull/8/commits/cef462074275ef20e2351585dc09a04e8c8c1cc5#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L112
https://github.com/orozCoding/myportfolio/pull/8/commits/cef462074275ef20e2351585dc09a04e8c8c1cc5#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L133

- Text headings → We re-arrange the headings order for a better hierarchy.
https://github.com/orozCoding/myportfolio/pull/8/commits/c2360a19fb903f5093bed492342df0db200df882#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L72
https://github.com/orozCoding/myportfolio/pull/8/commits/c2360a19fb903f5093bed492342df0db200df882#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L93
https://github.com/orozCoding/myportfolio/pull/8/commits/c2360a19fb903f5093bed492342df0db200df882#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L114
https://github.com/orozCoding/myportfolio/pull/8/commits/c2360a19fb903f5093bed492342df0db200df882#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L135

- Color contrast → We adjusted the colors to have better contrast.
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L47
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L237
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L249
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L251
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L293
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L312
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L427
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L427

- Resize → We fixed the style in some buttons to fit bigger fonts.
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L244-L246
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L305-L307
https://github.com/orozCoding/myportfolio/pull/8/commits/2bbe3670ce5f8507e50740a3d790e068aff89b1d#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289L420-L422

- Interaction → Applied border to elements focused with keyboard navigation
https://github.com/orozCoding/myportfolio/pull/8/commits/534294d43784a02ca714ab88c7ba44c7e4daa6ee#diff-f6e4f9cac7473cf1fe513beba97669f195a6e1872bbd857c713d41e0f4b5d289R637

- Moving content → no issues found.
- Multimedia → no issues found.
- The basic structure of the page → no issues found.

_We are not sure if we are supposed to link the old code or the new code, so we are linked first the new code with the changes above this comment, and now we are linking also the old code lines after this comment_

- Page titles → We changed the title to a more descriptive title. https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L8

- Image text alternatives → We modified the alt attribute for several images to make them more descriptive.ç
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L32
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L70
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L91
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L112
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L133

- Text headings → We re-arrange the headings order for a better hierarchy.
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L72
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L93
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L114
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/index.html#L135

- Color contrast → We adjusted the colors to have better contrast.
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L47
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L237
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L249
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L251
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L293
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L310
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L312
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L425
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L427
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L446

- Resize → We fixed the style in some buttons to fit bigger fonts.
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L244-L246
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L305-L307
https://github.com/orozCoding/myportfolio/blob/d293e3bd5cd53c8070f1530a88d3fa041616617e/css/styles.css#L420-L422

- Interaction → no issues found.
- Moving content → no issues found.
- Multimedia → no issues found.
- The basic structure of the page → no issues found.

### CODE REVIEW

**Comment by ShoiraTa** [comment]
Hi team, 

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Sadly, there are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

-  Based on project requirements, in pull request you had to put links to corresponding changes: 
image

- [ ] Please add the missing links ☀️ 
 
***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by orozCoding** [comment]
Thank you @ShoiraTa! Somehow we forgot about it 😮 

We just edited the pull-request description ✔️ 

We weren't sure if we have to add links to the previous code or to the new one so we linked both 😅

**Review by keneogu — APPROVED** [review]
## Status: Approved ✔️
Hi @orozCoding,

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations! 🎉💯🌟

### Good Points 👍
Project is set up correctly ✔️
Descriptive Pull Request title and summary✔️
No linter errors ✔️

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

-------

**Comment by ShoiraTa** [comment]
Wow you have done a a big job, kudos on that 👏🏻

**Pull request merged**
